FROM python:3.10-slim

WORKDIR /app

# Installe les dépendances système
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copie les fichiers
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose le port si nécessaire
EXPOSE 8000

CMD ["python", "quickstart.py"]